### ISSUE TITLE
Will it be possible to use TouchID instead of the password?

### ISSUE THREAD

**Issue by TomDeBe** [l3wi/iotaMobile#11]
Lewis Freiberg [16:37] 
Yes
Please submit an issue for that. :)

**Comment by l3wi** [comment]
I've had a look into the matter. The touchID library available to me gives me a simple true/false when a scan is performed. 

The way the application is setup, breaching the application sandbox will not give the attacker the seed (unless the password is still in memory). This is due to the seed being encrypted with the password.

Using the touchID method would remove the password protection of the seed. As there is no 'secret' that could be used to encrypt the seed. If touchID returned me a value for the fingerprint "agazKJAG8a783hlA8oah..." I'd be able to use that. 

So either I reduce the security of the seed or not implement this. I feel that while ease of use is nice security trumps it.

**Comment by l3wi** [comment]
Additionally heres an stack overflow on the [topic](https://security.stackexchange.com/questions/43587/is-iphones-fingerprint-signature-a-one-way-hash)
